config/routes.rb
Pinteresting::Application.routes.draw do
  mount RailsAdmin::Engine => '/_admin', as: 'rails_admin'
  resources :crms do
    collection { post :import }
  end
  resources :pins

  devise_for :users
  devise_for :views
  root "pins#index"
  get "about" => "pages#about"
  get "team" => "pages#team"
  
  get "pages/new_release" => 'pages#new_release', :as => :new_release

  

end

app/models/crm.rb
class Crm < ActiveRecord::Base

def self.import(file)
  allowed_attributes = [ "title","summary","rating","created_at","updated_at"]
  spreadsheet = open_spreadsheet(file)
  header = spreadsheet.row(1)
  (2..spreadsheet.last_row).each do |i|
    row = Hash[[header, spreadsheet.row(i)].transpose]
    crm = find_by_id(row["id"]) || new
    crm.attributes = row.to_hash.select { |k,v| allowed_attributes.include? k }
    crm.save!
  end
end

def self.open_spreadsheet(file)
  case File.extname(file.original_filename)
  when ".csv" then Roo::Csv.new(file.path, nil, :ignore)
  when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
  when ".xlsx" then Roo::Excelx.new(file.path, nil, :ignore)
  else raise "Unknown file type: #{file.original_filename}"
  end
end


end

app/models/pin.rb
class Pin < ActiveRecord::Base
	Paperclip.options[:command_path] = 'C:/Program Files/ImageMagick-6.8.5-Q16'
	belongs_to :user

	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
	has_attached_file :blurimage




	def self.search(search)
	  if search
	    where '"description" LIKE ?', "%#{search}%"
	  else
	    find(:all)
	  end
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	has_many :pins

	validates :name, presence: true
end

app/models/view.rb
class View < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end





end

app/controllers/crms_controller.rb
class CrmsController < ApplicationController
  before_action :set_crm, only: [:show, :edit, :update, :destroy]


  def index
    @crms = Crm.all
  end

def import
  Crm.import(params[:file])
  redirect_to root_url, notice: "crms imported."
end



  def show
  end

  def new
    @crm = Crm.new
  end


  def edit
  end

  def create
    @crm = Crm.new(crm_params)

    respond_to do |format|
      if @crm.save
        format.html { redirect_to @crm, notice: 'Crm was successfully created.' }
        format.json { render action: 'show', status: :created, location: @crm }
      else
        format.html { render action: 'new' }
        format.json { render json: @crm.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @crm.update(crm_params)
        format.html { redirect_to @crm, notice: 'Crm was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @crm.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @crm.destroy
    respond_to do |format|
      format.html { redirect_to crms_url }
      format.json { head :no_content }
    end
  end

  private
    def set_crm
      @crm = Crm.find(params[:id])
    end

    def crm_params
      params.require(:crm).permit(:title, :summary, :rating)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def team
  end

  def new_release
    respond_to do |format|
      format.html
      format.js
    end
  end


end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @pins = Pin.search(params[:search])
    #Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 8)

  end

  def crm
    @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 8)
  end

  def show
  end

  def new
    @pin = current_user.pins.build
    

  end

  def edit
    
  end

  def create
    @pin = current_user.pins.build(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pin }
      else
        format.html { render action: 'new' }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  def correct_user
    @pin = current_user.pins.find_by(params(:id))
    redirect_to pins_path if @pin.nil? notice: "not authorised to edit this pin"
  end


  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image, :pricing, :user_review_summary, :blurimage)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crms_helper.rb
module CrmsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/crms/_form.html.erb
<%= form_for(@crm) do |f| %>
  <% if @crm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@crm.errors.count, "error") %> prohibited this crm from being saved:</h2>

      <ul>
      <% @crm.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :summary %><br>
    <%= f.text_field :summary %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.number_field :rating %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/crms/edit.html.erb
<h1>Editing crm</h1>

<%= render 'form' %>

<%= link_to 'Show', @crm %> |
<%= link_to 'Back', crms_path %>

app/views/crms/index.html.erb
<h1>Listing crms</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Summary</th>
      <th>Rating</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @crms.each do |crm| %>
      <tr>
        <td><%= crm.title %></td>
        <td><%= crm.summary %></td>
        <td><%= crm.rating %></td>
        <td><%= link_to 'Show', crm %></td>
        <td><%= link_to 'Edit', edit_crm_path(crm) %></td>
        <td><%= link_to 'Destroy', crm, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Crm', new_crm_path %>

<h2>Import CRMs</h2>

<%= form_tag import_crms_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>

app/views/crms/new.html.erb
<h1>New crm</h1>

<%= render 'form' %>

<%= link_to 'Back', crms_path %>

app/views/crms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @crm.title %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @crm.summary %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @crm.rating %>
</p>

<%= link_to 'Edit', edit_crm_path(@crm) %> |
<%= link_to 'Back', crms_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">Contratado.me</a>
    </div>


    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home-new", root_path %></li>
          <li><%= link_to "About", about_path %></li>
          
          <% if user_signed_in? %>
                  
            <% if current_user.admin? %>
              <li><%= link_to new_pin_path do %>
                <span class="glyphicon glyphicon-plus"></span> New Pin
            <% end %>
            <% end %>
            </li>

            <li><%= link_to "Account", edit_user_registration_path %></li>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Sign in", new_user_session_path %></li>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
           <% end %>
  


        </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinteresting</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>


<%= render 'layouts/header' %>	



	
	<div class="container">
		<% flash.each do |name, msg| %>
		<%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>
		<%= yield %>
	</div>
	



</body>
</html>

app/views/pages/_new_release.html.erb
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Modal title</h4>
      </div>
      <div class="modal-body">
        <iframe src="https://contaazul.com">
        <p>Placeholder text; only shows up if the page DOESN'T render!</p>
        </iframe>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->


app/views/pages/about.html.erb
<h1>About us</h1>
<p>We are working on our one month rails app from the tutorial </p>

<%= link_to 'Add release', new_release_path,  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window'}  %>

<div id="modal-window" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

</div>

</div>

app/views/pages/home.html.erb
#Note - pretty sure there is no link to this file anywhere

<div class="jumbotron center">
<h1>Welcome to my app</h1>


<p>
	<%= link_to "Log in", new_user_session_path, class: "btn btn-primary btn-lg btn-block"%>
	<%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg btn-block"%>
</p>



<%= form_tag pins_path, method: "get" do %>
  <%= label_tag(:search, "Search for:") %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag("Search") %>
<% end %>



</div>

app/views/pages/new_release.js.erb
$("#modal-window").html("<%= escape_javascript(render 'pages/new_release') %>");

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label :blurimage %>
    <%= f.file_field :blurimage %>
  </div>
 
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :pricing %><br>
    <%= f.text_field :pricing %>
  </div>

  <div class="field">
    <%= f.label :user_review_summary %><br>
    <%= f.text_field :user_review_summary %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pins/_hidden.html.erb

  <div class="well well-header well-listing" >

    <div class="table-responsive" style="position: relative; left: 0; top: 0;">
      <table table class="table">
      <tr>
      <td>Best for</td>
      <td><%= image_tag @pin.blurimage.url %></td>
      </tr>
      <tr>
      <td>Pricing</td>
      <td><%= image_tag @pin.blurimage.url %></td>
      </tr>
      <tr>
      <td>English / portuguese</td>
      <td><%= image_tag @pin.blurimage.url %></td>
      </tr>
      <tr>
      <td>User reviews</td>
      <td><%= image_tag @pin.blurimage.url %></td>
      </tr>
      <tr>
      <td>Support coverage</td>
      <td><%= image_tag @pin.blurimage.url %></td>
      </tr>
      <tr>
      <td>Size of company</td>
      <td><%= image_tag @pin.blurimage.url %></td>
      </tr>
      <tr>
      <td>Compare with others</td>
      <td><%= image_tag @pin.blurimage.url %></td>
      </tr>
      </table>

      <div style="position: absolute; top: 100px; left: 600px;">
      <%= link_to "Register for full details", new_user_registration_path, class: "btn btn-success" %> 
      </div>


    </div>
  </div>

app/views/pins/_revealed.html.erb
<div class="well well-header well-listing" >
  <div class="table-responsive">
      <table table class="table">
      <tr>
      <td>Best for</td>
      <td>Test text</td>
      </tr>
      <tr>
      <td>Pricing</td>
      <td><%= @pin.pricing %></td>
      </tr>
      <tr>
      <td>English / portuguese</td>
      <td>Test text</td>
      </tr>
      <tr>
      <td>User reviews</td>
      <td><%= @pin.user_review_summary %></td>
      </tr>
      <tr>
      <td>Support coverage</td>
      <td>Test text</td>
      </tr>
      <tr>
      <td>Size of company</td>
      <td>Test text</td>
      </tr>
      <tr>
      <td>Compare with others</td>
      <td>Test text</td>
      </tr>
      </table>
  </div>
</div>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<%= render 'pages/home' %>




</div>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<%= link_to 'Back', pins_path %>

<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      
      <div class="panel-heading center">
        <%= image_tag @pin.image.url(:medium) %>
      </div>


      
      
        <div class="panel-title center">

          <p><strong><h3><%= @pin.description %></h3></strong></p>

        </div>

        <div class="panel-body">
          <p><strong><%= @pin.user.name if @pin.user %></strong></p>

          <% if current_user.admin? %>
          <%= link_to edit_pin_path(@pin) do %>
          <span class="glyphicon glyphicon-edit"></span>
          Edit
        	<% end %>
          <% end %>
        </div>
    </div>
  </div>
</div>


<%= render 'hidden' unless user_signed_in? %>
<%= render 'revealed' if user_signed_in? %>